# Generated by Django 3.1.7 on 2021-02-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
