# Generated by Django 3.1.7 on 2021-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210227_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='code',
            field=models.IntegerField(default=312, max_length=4),
        ),
    ]
