# Generated by Django 3.1.7 on 2021-02-27 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20210227_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='code',
            field=models.PositiveIntegerField(default=312, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
