# Generated by Django 3.1.7 on 2021-02-27 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20210227_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
