# Generated by Django 3.1.7 on 2021-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_auto_20210227_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
